# Site settings
title: Computer Science 291A

description: > # this means to ignore newlines until "baseurl:"
  Scalable Internet Services, CS291A, Fall 2016

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://cs291.com" # the base hostname & protocol for your site

github_username:  scalableinternetservices

instructor: "Bryce Boe"
instructor_url: "http://bryceboe.com"

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap