# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cs291.com # the base hostname & protocol for your site

# User settings
course_number: CS291A
quarter: Fall 2023
title: Scalable Internet Services

github_username: scalableinternetservices

instructor: Dr. Shyr-Shea Chang
instructor_email: shyr-shea.chang@appfolio.com
instructor_url: https://www.linkedin.com/in/shyr-shea-chang-6426271b8/

drive_url: https://drive.google.com/drive/folders/1gXSc42m6tDJMPPxE486C0YQ5KXxB92J2?usp=sharing
piazza_url: https://piazza.com/class/lllfmvbxvh83oq

intro_survey: https://forms.gle/93PrP7Td5tmvAqAFA
project0_submission: https://forms.gle/vzB1UtGre5Psg5pr8
project1_submission: https://forms.gle/GEj7s15jfG6xERjc8
project2_submission: https://forms.gle/RhsrS5CQHR4NY5oV8
project3_submission: https://forms.gle/jY5u11UGuskAfN7r7
project3_team_message: https://forms.gle/V5qHuDgm2NbZtTJH9

kramdown:
  parse_block_html: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
