# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://cs291.com # the base hostname & protocol for your site

# User settings
course_number: CS291A
quarter: Fall 2025
title: Scalable Internet Services
class_location: Phelps 2510

github_username: scalableinternetservices

instructor: Zach Walker
instructor_email: zach_walker@ucsb.edu
instructor_url: https://www.linkedin.com/in/zachary-walker-6a219059/

drive_url:
piazza_url: https://piazza.com/ucsb/fall2025/cs291a

intro_survey: https://forms.gle/TyxFWZnkW9qaqBhE7
project1_submission: https://forms.gle/8Z3TVU6kKxmX5Nro7
project2_submission: https://forms.gle/LAfXThZgjZASmVby5
project3_submission: https://forms.gle/hicZ2SNaVhb3ApXQ7
project4_submission: 
project5_team_message: 
initial_peer_review: 
peer_review: 

# Page visibility settings
navigable_pages:
  schedule: true
  project1: true
  project2: true
  project3: true
  project4: true
  project5: true

kramdown:
  parse_block_html: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
