# Site settings
title: Computer Science 291A

description: > # this means to ignore newlines until "baseurl:"
  Scalable Internet Services, CS291A, Fall 2018

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://cs291.com" # the base hostname & protocol for your site

github_username:  scalableinternetservices

instructor: "Bryce Boe"
instructor_url: "https://bryceboe.com"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
